trigger:
- none

pool:
  name: 'Default'  
  demands:
  - agent.name -equals myagent

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Instalando Node.js'

- task: CacheBeta@1
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    path: '$(Build.SourcesDirectory)/node_modules'
  displayName: 'Cache das dependencias do NPM para acelerar o build'

- task: Npm@1
  inputs:
    command: 'ci'
  displayName: 'clean & install'

- task: Npm@1
  inputs:
    command: 'run-script'
    customCommand: 'lint'
  displayName: 'Teste de qualidade'

- task: Npm@1
  inputs:
    command: 'test'
  displayName: 'Verificando a integridade do codigo'

- task: Npm@1
  inputs:
    command: 'run-script'
    customCommand: 'build'
  displayName: 'Build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copiando os arquivos do projeto'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publicando o artefato npm'

- task: AzureDevOpsNotifications@1
  inputs:
    message: 'Build $(Build.BuildNumber) completed with status $(Build.Status)'
  displayName: 'Envio de notificacoes do estado do build'